### ISSUE TITLE
Corrupted asset.meta?

### ISSUE THREAD

**Issue by b00064153-dev** [SabiKov/HumanEvolution#6] opened 2015-10-04 17:49 UTC
Made a second private branch from master and encountered an issue with scene_10.
Unity Editor gives out about missing ':' (colon) on line 2.
I had a look at the file on master branch and found some extra text in the .meta, lines 2, 5 and 8 specifically. Looks like git info. There are also 2 guid's and 2 timecreated. I deleted the second guid as in other metas it's on line 2.Not sure which timecreated is wrong but assuming the second one.
I think closing and reopening unity fixes the issue but it's still in the master at the moment.
Screenshot posted to Basecamp.

**Comment by SabiKov** [comment] 2015-10-05 00:37
Well, I haven't got any problem since the last time, actually I had some diff issue "2 sounds files are attached to the terrain" it was automatically solved by unity. I don't think if we re-initial the master branch the problem will be solved, on the other hand everyone has done something therefore I would not like to ask anyone to recreate prefabs or other objects. Furthermore, deleting .meta it is not the best approach for unity,  because these .metas are  generated on the OS platform. I suppose that different OSs (Win7, Win8.1 and Win10) make the problem. Just leave there let the unity solve the problem.

**Comment by b00064153-dev** [comment] 2015-10-05 14:30
I'm not suggesting removing the file just merging a branch without the error into master.
As mentioned, making branches of the master as it is now means the error is also in any new branches.

**Comment by daraghwalshe** [comment] 2015-10-05 16:59
Hi Guys
I've been looking into this today. There were two scene 10's in my local unity folder, possibly caused by  a branch merge after organising scene 10 into the scenes folder last week. Now working with my local repo I have deleted scene_4(empty scene), renamed the latest scene_10(the stepped blocks scene) to scene 4, as this is what my scene will be. I then deleted the remaining scene_10.
No complaints whatsoever from unity on closing/opening the project/scenes after these changes.
Two IMPORTANT things to note here are that 
1 -- any removal of assets should be done ONLY through the unity editor as this will also removed any associated meta files correctly.
2 -- Sabi. Make sure you are the only person who can merge with the master.

**Comment by daraghwalshe** [comment] 2015-10-05 16:59
Oops, I assume this issue is still open ?

**Comment by SabiKov** [comment] 2015-10-05 18:06
Only one way to change the permission above the merge function if we turn into organization, which I did(you received an email). But the major problem with that I need to create a new repository where I will try to add my sub-branch it is called "scene_environment_something" From this point I can fully control all settings, I think so. By the way, I'm going to wait until next meeting and we discuss/vote this issue. In other word I will create and we will test it on Friday. Alternative use-case scenario every adult should be able to control his fingers therefore don't press MERGE button/icon/image/whatsoever please!

**Closed** 2015-10-14 13:05 UTC
